<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "geo_ip_handler"
 *
 * Auto generated by Extension Builder 2019-05-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Geo IP Handler',
    'description' => '',
    'category' => 'plugin',
    'author' => '',
    'author_email' => '',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
    'autoload' =>[
	'psr-4' =>[
	  "GeoIp2\\"=> "Libraries/geoip2/src",
	  "MaxMind\\"=> "Libraries/geoip2/maxmind-db",
	  "KK\\GeoIpHandler\\"=> "Classes"
	]
    ]
];
